### ISSUE TITLE
RelayParser Error

### ISSUE THREAD

**Issue by tshamz** [AlexanderProd/gatsby-shopify-starter#1]
Hi, just wanted to start by saying I'm a huge fan of this starter.

However, after getting started with:
`gatsby new my-shopify-store https://github.com/AlexanderProd/gatsby-shopify-starter`

and then switching directories and running `gatsby develop`, I get about 75% of the way through the initial compilation process and then I run into this error:

```
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- usersTylershamboraCodeShopifyCutsGatsbySrcTemplatesProductPageIndexJs3430434902
```

It's coming right after the update schema lifecycle method when dynamically creating the pages:
```
success source and transform nodes — 10.678 s
success building schema — 0.651 s
success createPages — 0.161 s
success createPagesStatefully — 0.026 s
success onPreExtractQueries — 0.003 s
success update schema — 0.483 s
error GraphQL Error There was an error while compiling your site's GraphQL queries.
```

For now I've just commented out the graphql query inside of template/productPage, which gets me through the initial compile so I can noodle around a bit. It's been a couple of months since I've touched gatsby related so I'm getting reacquainted for now, but I'll keep poking around on this and see if I can find anything else out.

🙏🏻

**Comment by AlexanderProd** [comment]
This is a [error in Gatsby](https://github.com/gatsbyjs/gatsby/issues/11688) at the moment, you can workaround it by replacing `./src/templates/ProductPage/index.js` with `./src/templates/productPage/index.js` notice the small `p` inside the `gatsby-node.js` file. 

Unfortunately I cant push the workaround because the workaround breaks it on my machine.
