### ISSUE TITLE
Add To Cart button needs to be disabled when adding item to cart

### ISSUE THREAD

**Issue by gregleeper** [AlexanderProd/gatsby-shopify-starter#14]
I've noticed that when a user clicks the Add To Cart button and then clicks again before the item is done adding it erases the contents of the cart and nothing gets added. This is noticeable on slower connection speeds.

`
<button
              className="btn btn-primary"
              type="submit"
              disabled={!available || context.adding}
              onClick={handleAddToCart}
            >
              Add to Cart
</button>
`

**Comment by AlexanderProd** [comment]
Thanks for the suggestion, I‘ll implement it.

**Comment by gregleeper** [comment]
👍Thanks for the awesome starter! You saved me a ton of time.
