### ISSUE TITLE
SEO Topics

### ISSUE THREAD

**Issue by Chompas** [AlexanderProd/gatsby-shopify-starter#19]
Hi, I'm not sure how to get SEO details from the products when listing them in a details page. Any help would be appreciated.

**Comment by AlexanderProd** [comment]
I‘m currently investigating the best practices of SEO with gatsby and how to make use of the Shopify data. I’ll report back.

**Comment by AlexanderProd** [comment]
The page title and description of a product page is now being hydrated with the data from Shopify.

**Comment by AlexanderProd** [comment]
closed because of inactivity
