### ISSUE TITLE
Problems with multiple duplicate items in cart

### ISSUE THREAD

**Issue by dakovi** [AlexanderProd/gatsby-shopify-starter#2]
First of all thank you for providing this awesome starter as an inspiration.

I've come across two problems with the current version:

1. There is no real representation of the item quantity in the cart itself (https://gatsby-shopify.alexander-productions.de/cart). This causes problems if I add more than one item of the same type (e.g. "DOUBLE RACER BACK DRESS 2 / Black") to my cart since buyers aren't able to see this info.

2. The counter for the items in the cart in the top right corner next to the cart icon ignores duplicate items. Therefore adding an item twice (or more) doesn't increase the size of the counter. It is raised only once when adding an item for the first time.

Greetings

**Comment by AlexanderProd** [comment]
Oh yeah you’re right, I’m going to fix this.

**Comment by nachiketkumar** [comment]
> Oh yeah you’re right, I’m going to fix this.

Has this been updated/fixed @AlexanderProd? Thanks for this starter!

**Comment by AlexanderProd** [comment]
Hi @nachiketkumar 
I'm glad you like my starter! I've just pushed a fix for the counter not showing multiple items.

**Comment by AlexanderProd** [comment]
Nevermind I've noticed it still persists if more items of the exact same type are added.

**Comment by nachiketkumar** [comment]
@AlexanderProd any luck in getting this sorted out?

**Comment by AlexanderProd** [comment]
I’ve quickly looked over the problem but haven’t found a fast solution yet. Unfortunately I don’t have time to focus on this problem atm because of finals.

**Comment by AlexanderProd** [comment]
Fixed, the counter is correct now and the cart shows quantity of individual items.
