### ISSUE TITLE
Shop should update new products in real time

### ISSUE THREAD

**Issue by kingingcole** [AlexanderProd/gatsby-shopify-starter#23]
Apart from real-time update of inventories, the site should also update new products added in the shopify dashboard. Right now, I need to rebuild on Netlify each time I add a new product from the Shopify dashboard.

**Comment by AlexanderProd** [comment]
You can trigger a rebuild on Netlify automatically by adding a webhook to Shopify which can be triggered with certain actions like when you create a new product.

Am 02.11.2019 um 15:39 schrieb kingingcole <notifications@github.com>:

﻿

Apart from real-time update of inventories, the site should also update new products added in the shopify dashboard. Right now, I need to rebuild on Netlify each time I add a new product from the Shopify dashboard.

**Comment by kingingcole** [comment]
On creating a webhook in Shopify, they asked for an URL. What should I use here that should link it to Netlify?

**Comment by AlexanderProd** [comment]
On your Netlify dashboard you can create webhook urls that trigger a rebuild.

**Comment by kingingcole** [comment]
Hey. Just found it! Thanks for your help!
