### ISSUE TITLE
Add Documentation on Shopify Access rights

### ISSUE THREAD

**Issue by stcalica** [AlexanderProd/gatsby-shopify-starter#24]
Do we need write access for orders and products in the Shopify Admin area? 
I want to not add any extra permissions and leave my store exposed.

**Comment by AlexanderProd** [comment]
No, you need to use Shopify storefront API not the regular Shopify API. The storefront API doesn’t include write access to products and orders.

**Comment by stcalica** [comment]
solved. correct, I was in the wrong section
