### ISSUE TITLE
Timeout query GetCollections - Shopify

### ISSUE THREAD

**Issue by rownco** [AlexanderProd/gatsby-shopify-starter#25]
I've installed this successfully however once I change the credentials and rebuild, I'm getting the following error:

> ERROR 
> 
> 
> error an error occurred while sourcing data
> 
> 
>  ERROR 
> 
> - 
>   message: Timeout
> 
> 
>  ERROR 
> 
> query: 
>   """
> 
>       query GetCollections($first: Int!, $after: String) {
>         shop {
>           collections(first: $first, after: $after) {
>             pageInfo {
>               hasNextPage
>             }
>             edges {
>               cursor
>               node {
>                 description
>                 descriptionHtml
>                 handle
>                 id
>                 image {
>                   altText
>                   id
>                   src
>                 }
>                 products(first: 250) {
>                   edges {
>                     node {
>                       id
>                     }
>                   }
>                 }
>                 title
>                 updatedAt
>               }
>             }
>           }
>         }
>       }
> 
>   """
> variables: 
>   first: 100
>   after: null

Adding paginationSize: 100 helps slightly; it begins fetching and then after 15 seconds it returns the above error.

The store I'm trying this on is a Shopify Plus store, and has 8500 products & 3200 collections. I've also had the api limits increased by Shopify.

Any ideas on why this isn't working and how I can resolve would be much appreciated!

**Comment by AlexanderProd** [comment]
Unfortunately I’ve never encountered a bug like this, but I’ve also never tried the starter with Shopify store as big as yours. Maybe it’s because of the size. Maybe you can open an issue with [gatsby-source-shopify](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify) since the problem should be located there, rather than the starter.

**Comment by kingingcole** [comment]
Hello Alex. i am also experiencing this issue with a shopify store for a client.

**Comment by AlexanderProd** [comment]
@rownco Could you fix the error?

**Comment by AlexanderProd** [comment]
@kingingcole How many collections does the store have?

**Comment by AlexanderProd** [comment]
closed because of inactivity

**Comment by rownco** [comment]
No I didn't find a solution for this, any ideas appreciated.

**Comment by emilymaskin** [comment]
I'm having the same issue, also a large store...
