### ISSUE TITLE
Add theme settings to customize with Shopify

### ISSUE THREAD

**Issue by Acidic9** [AlexanderProd/gatsby-shopify-starter#27]
Can you use theme settings to enable the user to customize the site?

Such as this: https://help.shopify.com/en/themes/development/theme-editor/settings-schema

**Comment by AlexanderProd** [comment]
This repository is not a Shopify theme, it's a Gatsby site that uses the Shopify Storefront api to display the content. A Shopify theme requires you to use the built in Shop feature (the website) in Shopify.
