### ISSUE TITLE
Just a cascade of errors after changing credentials

### ISSUE THREAD

**Issue by radmedov** [AlexanderProd/gatsby-shopify-starter#3]
Everything works fine until I put my real credentials.
Getting a bunch of errors: 
Encountered an error trying to infer a GraphQL type for: "products___NODE". There is no corresponding node with the id field matching: "Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0MjY4MDM4MTE= ......

error UNHANDLED REJECTION
Invariant Violation: Encountered an error trying to infer a GraphQL type for: "products___NODE". There is no corresponding node with the id field matching: "Shopify__Product__Z2lkOi  8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0MjY4MDM4MTE=

Any pieces of advice would be appreciated.

Thank you

**Comment by AlexanderProd** [comment]
Hi,

Try deleting the cache folder before running it again after changing the credentials.

**Comment by radmedov** [comment]
@AlexanderProd No luck. Same errors

**Comment by AlexanderProd** [comment]
Does every product on your Shopify store have at least one product image? Currently the starter crashes if there are products without images. 

Also did you use the storefront api credentials and not the ones for the regular shopify api?

Running `npx gatsby clean` might be worth a try as well.

**Comment by radmedov** [comment]
Yes and yes. 
BTW is there any way to set a placeholder by default to prevent a crash if there's no image?

**Comment by AlexanderProd** [comment]
I dont know about placeholder images in Shopify. It would be easily escapable in gatsby though. 
Does the bug still happen? If so can you maybe post the whole error log?

**Comment by radmedov** [comment]
There you go
`  gatsby git:(master) ✗ gatsby develop
success open and validate gatsby-configs — 0.007 s
success load plugins — 0.182 s
success onPreInit — 0.227 s
success initialize cache — 0.011 s
success copy gatsby files — 0.062 s
success onPreBootstrap — 0.004 s
⠁
gatsby-source-shopify/alogives starting to fetch data from Shopify
⠠ source and transform nodes
gatsby-source-shopify/alogives fetched and processed policies: 280.146ms
⠐ source and transform nodes
gatsby-source-shopify/alogives fetched and processed articles: 367.408ms
⠁ source and transform nodes
gatsby-source-shopify/alogives fetched and processed blogs: 455.109ms
⠐ source and transform nodes
gatsby-source-shopify/alogives fetched and processed collections: 824.394ms

gatsby-source-shopify/alogives fetched and processed productTypes: 859.764ms
⡀ source and transform nodes
error an error occured while sourcing data
-
  message: Timeout
query:
  """

      query GetProducts($first: Int!, $after: String) {
        shop {
          products(first: $first, after: $after) {
            pageInfo {
              hasNextPage
            }
            edges {
              cursor
              node {
                createdAt
                description
                descriptionHtml
                handle
                id
                images(first: 250) {
                  edges {
                    node {
                      id
                      altText
                      originalSrc
                    }
                  }
                }
                onlineStoreUrl
                options {
                  id
                  name
                  values
                }
                priceRange {
                  minVariantPrice {
                    amount
                    currencyCode
                  }
                  maxVariantPrice {
                    amount
                    currencyCode
                  }
                }
                productType
                publishedAt
                tags
                title
                updatedAt
                variants(first: 250) {
                  edges {
                    node {
                      availableForSale
                      compareAtPrice
                      id
                      image {
                        altText
                        id
                        originalSrc
                      }
                      price
                      selectedOptions {
                        name
                        value
                      }
                      sku
                      title
                      weight
                      weightUnit
                    }
                  }
                }
                vendor
              }
            }
          }
        }
      }

  """
variables:
  first: 250
success source and transform nodes — 37.212 s
error Encountered an error trying to infer a GraphQL type for: "products___NODE". There is no corresponding node with the id field matching: "Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYxODc3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUyMTA0Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjUwMjUzNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTIxMDg2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQ2NzYwNjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTg1MTQyNzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTgwMjI3NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTc4OTE2ODM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYzODQzNTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYyNTMyODM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYxODc3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTEyMzk3Nzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTA4NDY1NjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDk1MzU4NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDkwNDQzMjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDU4MzMwNTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUyMTA0Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUwNzkzOTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDM0NDA5OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDI3MjAwOTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDIyOTQxMTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDA5MTc4NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3Mzg3ODc5Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzY2MjUyNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzU3NDA1MTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzIzMzI2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjUwMjUzNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjM5NzY4MDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MTYxNDUyNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDk1MjYxMTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDMzMDAxOTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDExNzAyNzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MzQzMjM1NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MTY5MjM3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MDI2MzY4OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MDAxNzkyOTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1ODExNzM4NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTIxMDg2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTAzMDY0MDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NDAyNDY2Mjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1Mzk4ODYxNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1Mzk0Mjc0Mjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzU5ODY3ODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzU1OTM1NzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQ2NzYwNjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQxMTkwMTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzM5ODc5Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTg5MTQ2NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTg2MTk3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTU5NjU1Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTA4ODY0OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTA3MjI2NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTAzNjIyMTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0OTI3MzMwMjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0NzU0NjQyOTE="


  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "products___NODE". There is no corresponding node with the id field matching: "Shopify__Product__Z2lkOi  8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYxODc3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUyMTA0Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjUwMjUzNzk=,Shopify__Pr  oduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTIxMDg2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQ2NzYwNjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTg1MTQyNzU  =,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTgwMjI3NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTc4OTE2ODM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OT  E3NTYzODQzNTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYyNTMyODM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYxODc3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qc  m9kdWN0LzE0OTE3NTEyMzk3Nzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTA4NDY1NjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDk1MzU4NDM=,Shopify__Product__Z2lkOi8v  c2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDkwNDQzMjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDU4MzMwNTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUyMTA0Njc=,Shopify__Prod  uct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUwNzkzOTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDM0NDA5OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDI3MjAwOTk=,  Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDIyOTQxMTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDA5MTc4NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3  Mzg3ODc5Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzY2MjUyNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzU3NDA1MTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9  kdWN0LzE0OTE3MzIzMzI2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjUwMjUzNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjM5NzY4MDM=,Shopify__Product__Z2lkOi8vc2  hvcGlmeS9Qcm9kdWN0LzE0OTE3MTYxNDUyNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDk1MjYxMTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDMzMDAxOTU=,Shopify__Produc  t__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDExNzAyNzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MzQzMjM1NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MTY5MjM3NDc=,Sh  opify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MDI2MzY4OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MDAxNzkyOTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1OD  ExNzM4NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTIxMDg2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTAzMDY0MDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kd  WN0LzE0OTE1NDAyNDY2Mjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1Mzk4ODYxNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1Mzk0Mjc0Mjc=,Shopify__Product__Z2lkOi8vc2hv  cGlmeS9Qcm9kdWN0LzE0OTE1MzU5ODY3ODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzU1OTM1NzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQ2NzYwNjc=,Shopify__Product_  _Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQxMTkwMTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzM5ODc5Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTg5MTQ2NTk=,Shop  ify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTg2MTk3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTU5NjU1Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTA4  ODY0OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTA3MjI2NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTAzNjIyMTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN  0LzE0OTE0OTI3MzMwMjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0NzU0NjQyOTE="

  - invariant.js:40 invariant
    [gatsby]/[invariant]/invariant.js:40:15

  - infer-graphql-type.js:223 validateLinkedNode
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:223:5

  - infer-graphql-type.js:242 linkedNodes.forEach.node
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:242:33

  - Array.forEach

  - infer-graphql-type.js:242 inferFromFieldName
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:242:17

  - infer-graphql-type.js:345 _.each
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:345:23

  - lodash.js:4911
    [gatsby]/[lodash]/lodash.js:4911:15

  - lodash.js:2996 baseForOwn
    [gatsby]/[lodash]/lodash.js:2996:24

  - lodash.js:4880
    [gatsby]/[lodash]/lodash.js:4880:18

  - lodash.js:9344 Function.forEach
    [gatsby]/[lodash]/lodash.js:9344:14

  - infer-graphql-type.js:328 _inferObjectStructureFromNodes
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:328:5

  - infer-graphql-type.js:399 inferObjectStructureFromNodes
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:399:10

  - build-node-types.js:139 inferFields
    [gatsby]/[gatsby]/dist/schema/build-node-types.js:139:26

  - build-node-types.js:188 fields
    [gatsby]/[gatsby]/dist/schema/build-node-types.js:188:19


error UNHANDLED REJECTION


  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "products___NODE". There is no corresponding node with the id field matching: "Shopify__Product__Z2lkOi  8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYxODc3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUyMTA0Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjUwMjUzNzk=,Shopify__Pr  oduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTIxMDg2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQ2NzYwNjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTg1MTQyNzU  =,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTgwMjI3NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTc4OTE2ODM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OT  E3NTYzODQzNTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYyNTMyODM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTYxODc3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qc  m9kdWN0LzE0OTE3NTEyMzk3Nzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NTA4NDY1NjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDk1MzU4NDM=,Shopify__Product__Z2lkOi8v  c2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDkwNDQzMjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDU4MzMwNTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUyMTA0Njc=,Shopify__Prod  uct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDUwNzkzOTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDM0NDA5OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDI3MjAwOTk=,  Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDIyOTQxMTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3NDA5MTc4NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3  Mzg3ODc5Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzY2MjUyNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MzU3NDA1MTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9  kdWN0LzE0OTE3MzIzMzI2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjUwMjUzNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MjM5NzY4MDM=,Shopify__Product__Z2lkOi8vc2  hvcGlmeS9Qcm9kdWN0LzE0OTE3MTYxNDUyNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDk1MjYxMTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDMzMDAxOTU=,Shopify__Produc  t__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE3MDExNzAyNzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MzQzMjM1NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MTY5MjM3NDc=,Sh  opify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MDI2MzY4OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE2MDAxNzkyOTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1OD  ExNzM4NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTIxMDg2NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1NTAzMDY0MDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kd  WN0LzE0OTE1NDAyNDY2Mjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1Mzk4ODYxNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1Mzk0Mjc0Mjc=,Shopify__Product__Z2lkOi8vc2hv  cGlmeS9Qcm9kdWN0LzE0OTE1MzU5ODY3ODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzU1OTM1NzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQ2NzYwNjc=,Shopify__Product_  _Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzQxMTkwMTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MzM5ODc5Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTg5MTQ2NTk=,Shop  ify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTg2MTk3NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTU5NjU1Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTA4  ODY0OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTA3MjI2NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE1MTAzNjIyMTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN  0LzE0OTE0OTI3MzMwMjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0NzU0NjQyOTE="

  - invariant.js:40 invariant
    [gatsby]/[invariant]/invariant.js:40:15

  - infer-graphql-type.js:223 validateLinkedNode
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:223:5

  - infer-graphql-type.js:242 linkedNodes.forEach.node
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:242:33

  - Array.forEach

  - infer-graphql-type.js:242 inferFromFieldName
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:242:17

  - infer-graphql-type.js:345 _.each
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:345:23

  - lodash.js:4911
    [gatsby]/[lodash]/lodash.js:4911:15

  - lodash.js:2996 baseForOwn
    [gatsby]/[lodash]/lodash.js:2996:24

  - lodash.js:4880
    [gatsby]/[lodash]/lodash.js:4880:18

  - lodash.js:9344 Function.forEach
    [gatsby]/[lodash]/lodash.js:9344:14

  - infer-graphql-type.js:328 _inferObjectStructureFromNodes
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:328:5

  - infer-graphql-type.js:399 inferObjectStructureFromNodes
    [gatsby]/[gatsby]/dist/schema/infer-graphql-type.js:399:10

  - build-node-types.js:139 inferFields
    [gatsby]/[gatsby]/dist/schema/build-node-types.js:139:26

  - build-node-types.js:188 fields
    [gatsby]/[gatsby]/dist/schema/build-node-types.js:188:19`

**Comment by AlexanderProd** [comment]
Can you maybe check what the GraphQL results for the product with this Id are `Shopify__Product__Z2lkOi 8vc2hvcGlmeS9Qcm9kdWN0LzE0OTE0MjY4MDM4MTE=` ? 
Maybe there's are problem with this product in particular? 

Also another possibility to check where the error comes might be to check if your credentials work with the [react-js-buy example](https://github.com/Shopify/storefront-api-examples/tree/master/react-js-buy) example from shopify.

**Comment by radmedov** [comment]
react-js-buy perfectly works

**Comment by radmedov** [comment]
@AlexanderProd Actually, it works so weirdly. Sometimes I'm getting an error(See attached)
<img width="932" alt="screen shot 2019-03-05 at 3 37 59 pm" src="https://user-images.githubusercontent.com/25644432/53845116-d388a680-3f5c-11e9-8d5d-fda3fd8b0bc3.png">

**Comment by radmedov** [comment]
I've got about 1000 products and each has in average 50 variants. Can it be an issue?

**Comment by AlexanderProd** [comment]
Oh I can definitely imagine react having issues creating the state for a product with 50 variants. I have never tested so many.

**Comment by radmedov** [comment]
Gotcha, will think about building from scratch

**Comment by dustinheisey** [comment]
has anyone found a solution to this problem? i only have three products and they all have images however this is still happening

**Comment by AlexanderProd** [comment]
Hi,

Can you please share your error message and what OS you’re using.

**Comment by aech12** [comment]
> has anyone found a solution to this problem? i only have three products and they all have images however this is still happening

I was having this problem but I was using the wrong authentication shopify token, so check in the docs if you're using the proper token

**Comment by zetorama** [comment]
@dustinheisey, I've also encountered similar problem, and my issues was related to Storefront API Permissions (specifically – `unauthenticated_read_product_tags` was disabled). So, try to check these as well in your Shopify dashboard.

**Comment by rajannahar** [comment]
I've cloned this project and I'm encountering issues too when I change the shopify credentials

`error GraphQL Error Encountered 2 error(s):
- Unknown field 'allShopifyProduct' on type 'Query'`

I updated the access token and shop name, I've cleaned out the .cache folder and even deleted node_modules and reinstalled.

Anyone having the same issue or managed to resolve this?

**Comment by AlexanderProd** [comment]
Hi,

This seems like you don’t have any products on your shopify page or at least no one that the api can access.

**Comment by rajannahar** [comment]
Hi @AlexanderProd 

If I hit `https://store-name.myshopify.com/admin/apps/shopify-graphiql-app` and query 
```
query {
  products(first: 10) {
    edges {
      node {
        id
        title
        totalInventory
        description
        featuredImage {
          id
        }
      }
    }
  }
}
```

I receive data back in the shopify graphl interface

However, if i hit `https://store-name.myshopify.com/admin/api/graphql.json` I get `{"errors":"Not Found"}`

Not quite sure what I'm doing wrong, can you help please?

**Comment by AlexanderProd** [comment]
Hi @rajannahar 

Does it still not work or could you fix it?

**Comment by rajannahar** [comment]
> Hi @rajannahar
> 
> Does it still not work or could you fix it?

Hi @AlexanderProd 
Yes, got it working in the end, I was using the wrong key after all that. 
I did also delete the .cache and node_modules too.

Thanks for helping!
