### ISSUE TITLE
Can't Get Query on metafields

### ISSUE THREAD

**Issue by 4nkit-5hukla** [AlexanderProd/gatsby-shopify-starter#32]
on
https://{shop}.myshopify.com/admin/apps/shopify-graphiql-app
{
  products(first: 10) {
    edges {
      node {
        title
        id
        handle
        metafield(namespace: "spr", key: "reviews") {
          key
          value
        }
      }
    }
  }
}
But I am still not able to query metafield in allShopifyProducts or allShopifyProduct in
http://localhost:8000/___graphql

**Comment by AlexanderProd** [comment]
It looks like the metafield property is not available with your GraphQL query. Whatever might be the case, it is definitely not a problem with the gatsby-shopify-starter but rather the `gatsby-source-shopify` plugin. I'd recommend you open up an error in the official [Gatsby](https://github.com/gatsbyjs/gatsby) repository.
