### ISSUE TITLE
Gatsby Develop very Slow with Shopify Starter

### ISSUE THREAD

**Issue by arhoy** [AlexanderProd/gatsby-shopify-starter#35]
Hello.
The Shopify Starter is extremely slow. It takes about 10 minutes to generate the image thumbnails? I s this typical for a site with about 1000 products?

**Comment by AlexanderProd** [comment]
Yes this sounds pretty normal given how much products your site has, 1000 is quite a a larger number and it has gl create different thumbnails for each picture. After all speed depends on how powerful your system is though.

**Comment by arhoy** [comment]
I am having issues with running Gatsby Develop in my local environment. This had made me wonder if it was a huge mistake to build the site in Gatsby in the first place. It is slow and I am running into lots of errors that does not happen when I connect to a smaller store

**Comment by arhoy** [comment]
There is also an issue fetching all the products from the Shopify CMS when I increased the number of products. Do you know why this could be?

Most sites on Shopify have 1000s of products from what I was told

**Comment by AlexanderProd** [comment]
I don't have experience with Gatsby and big Shopify stores with thousands of products myself. But it could well be the case that Gatsby is not the right solution there. Maybe you can research this a bit by contacting the developers of Gatsby and the Gatsby-Shopify-addon if their addon has been successfully been tested with 1000s of products. I'd be curious to know this too.
