### ISSUE TITLE
Get lineItem slug/handle in the checkout context

### ISSUE THREAD

**Issue by theskillwithin** [AlexanderProd/gatsby-shopify-starter#38]
I want to get the slug/handle of products in my checkout so that I can link to those items on my cart page, etc.

It appears that the following:
```
const fetchCheckout = (id) => store.client.checkout.fetch(id)
```

by default does not provide you the slug/handle of the products in the checkout. 

Seems like there might be a way to add to the query (https://github.com/Shopify/js-buy-sdk/issues/592)  but this is difficult to find example for checkout

**Comment by AlexanderProd** [comment]
You can now get to the product page by clicking on the image in the cart, this was what you wanted to do right?

**Comment by theskillwithin** [comment]
@AlexanderProd Perfecto!  thank you!!!
