### ISSUE TITLE
Custom check out and user dashboard in Gatsby.

### ISSUE THREAD

**Issue by PolGuixe** [AlexanderProd/gatsby-shopify-starter#4]
Would it be possible to build a custom checkout process and a user dashboard using Gatsby and the Shopify API?

**Comment by AlexanderProd** [comment]
Hi @PolGuixe, 

A custom checkout is not possible with the Shopify storefront API. Depending on what you want to do in the dashboard it might be possible.

**Comment by PolGuixe** [comment]
@AlexanderProd many thanks for the quick response.

So what they describe here https://help.shopify.com/en/api/storefront-api/guides/checkout-guide
just helps to get the checkout URL where the user should redirect to finish checkout, right?

Then in order to maintain a similar look&feel could the `checkoutUrl` be rendered into an `<iframe>`?

**Comment by AlexanderProd** [comment]
> So what they describe here https://help.shopify.com/en/api/storefront-api/guides/checkout-guide
> just helps to get the checkout URL where the user should redirect to finish checkout, right?

exactly 

> Then in order to maintain a similar look&feel could the checkoutUrl be rendered into an <iframe>?

Maybe this is possible but definitely discouraged from Shopify and it could have problems in regards to security when rendering the checkout process in an `<iframe>`. Chances are the checkout wouldn't even work in an `<iframe>`.

**Comment by PolGuixe** [comment]
> Maybe this is possible but definitely discouraged from Shopify and it could have problems in regards to security when rendering the checkout process in an <iframe>. Chances are the checkout wouldn't even work in an <iframe>.

I was worried about the same. It is just good to confirm it.
