### ISSUE TITLE
Image slider on productpage

### ISSUE THREAD

**Issue by wouter-dev** [AlexanderProd/gatsby-shopify-starter#40]
Hi,

Product images, on productpages, aren't shown in a slider at the larger breakpoints, only on mobile format. Changing the breakpoints.l to for instance s or xl does not fix it. /src/templates/ProductPage/index.js

```javascript
if (product.images) {
      return (
        <div>
          {width < breakpoints.l 
            ? <Slide {...properties}>
                {product.images.map(i => (
                  <Img
                    fluid={i.localFile.childImageSharp.fluid}
                    alt={product.title}
                    key={i.id}
                  />
                ))}
              </Slide>
            : product.images.map(image => (
              <Img
                fluid={image.localFile.childImageSharp.fluid}
                alt={product.title}
                key={image.id}
              />
            ))
          }
        </div>
      )
    }
  }
```

Any idea?

**Comment by AlexanderProd** [comment]
Yeah that’s because the slider is supposed to be only visible on smaller screens not on larger ones. :)

**Comment by wouter-dev** [comment]
I understand, but how do I make the slider visible on larger screens?

**Comment by AlexanderProd** [comment]
Well, I think you opened the issue in the wrong repo since the slider is not actually part of the gatsby shopify starter and the code you've shown neither. ;)
