### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by balibebas** [AlexanderProd/gatsby-shopify-starter#44]
First off, killer starter. Thoughtful design such as the currency internnationalization based off Shopify product price shine in the code. And having `@emotion/core` in place made adding web fonts and porting to Chakra a snap. Very nice work.

Have you considered converting this repo to TypeScript for a more solid footing? I understand you don't want to add too much opinoin but moving to TS is probably something most would do just for the benefit of static code checking. It's one of the first things I did when I started using it and a low-effort conversion given the limited customizations you've made to `gatsby-default-starter`.

**Comment by AlexanderProd** [comment]
I’ve actually thought about moving to TypeScript a lot because I’d prefer it too. But I don’t want scare of people who are just starting out and are more comfortable with JS. Maybe a good idea would be to create a second repo with the starter written in TS.

**Comment by balibebas** [comment]
Sounds good. I'll close this here.

**Comment by AlexanderProd** [comment]
I've started converting the starter to Typescript, you can follow along [here](https://github.com/AlexanderProd/gatsby-shopify-starter-ts).
