### ISSUE TITLE
Add copyright notice to license

### ISSUE THREAD

**Issue by balibebas** [AlexanderProd/gatsby-shopify-starter#45]
This is a great starter but as it stands the work added to the `gatsby-starter-default` is unclear from a licensing perspective given no copyright notice was added by the author. Please add a copyright notice. For more information see: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html. If you're unsure how to add a notice let me know and I'll help.

**Comment by AlexanderProd** [comment]
Sry I had no time to read all of that yet, but I do have a LICENSE file in the repo, or is the problem that it still says gatsbyjs instead of my name?

**Comment by balibebas** [comment]
It's an issue unless you're representing Gatsby because you're legally required to keep the `LICENSE` file from the starter you forked even if you don't intend to allow your changes to be used by others.

**Comment by AlexanderProd** [comment]
So it's wrong either way? I have to keep the LICENSE file the same because I forked it but I can't keep it because im not representing Gatsby?

**Comment by balibebas** [comment]
It just needs to be updated to show there are multiple authors if you want to continue under MIT. To update the license you would need to add another Copr line to the license text.

**Comment by AlexanderProd** [comment]
Thanks for you help, gonna look into that.

**Comment by balibebas** [comment]
Glad to help. There's some relevant discussion here: https://opensource.stackexchange.com/questions/1385/how-should-i-re-license-the-scaffold-code-for-my-new-application-it-is-license/1389#1389

**Comment by AlexanderProd** [comment]
Can you checkout if #46 looks good in case Gatsby doesn't relicense the starter to 0BSD?

**Comment by balibebas** [comment]
LGTM. I know you had a few contributors but their changes should be covered under the presumption they believed they were already contributing to an MIT-licensed work. FWIW if I had my way we'd abolish copyright in digital form so people could just develop software and not have to worry about this kind of stuff.

**Comment by AlexanderProd** [comment]
Thanks then I'll merge it. Didn't even think about the contributors another point that would make it complicated, but yeah you're right, seems like you have to be a lawyer just to put a good LICENSE file into a repo. lol

**Comment by balibebas** [comment]
@AlexanderProd FYI they moved to 0BSD so you can pull the `gatsbyjs` out of your license now if you like.

**Comment by AlexanderProd** [comment]
Thanks for letting me know, gonna get back to a regular MIT license file now.
