### ISSUE TITLE
Is the checkout opening in a new tab a technical limitation?

### ISSUE THREAD

**Issue by cordial** [AlexanderProd/gatsby-shopify-starter#47]
hey again!

I noticed you open the checkout using window.open and was wonder why you decided to load it in a new tab? Is it because if I were to open it in the same tab as the site, I would lose the ability to get back to the site after the checkout process? It isn't ideal having it in a different tab as it is but I was wondering if it is like this for a reason (I imagine there is one)?

**Comment by cordial** [comment]
Sorry, this is more a question that an issue.

**Comment by AlexanderProd** [comment]
Hey,

When using the Shopify checkout sdk, they want the checkout site to be loaded in a new tab instead of an iFrame. It’s not recommended to run the checkout in an iFrame in terms of security.

**Comment by cordial** [comment]
It can't just be run in the same tab as its on full page though?

**Comment by AlexanderProd** [comment]
Sure I guess you could do that, never thought much it tbh.
