### ISSUE TITLE
Build error on node v.12.0.0

### ISSUE THREAD

**Issue by dasdachs** [AlexanderProd/gatsby-shopify-starter#5]
When installing the dependencies using node `v12.0.0` I get several build errors. I set nvm to use the latest lts version, `v10.16.0` and I had no issues. 

I'll inspect the issue later today, but it seems it's a problem with the version of V8.

I suggest adding a `.nvmrc` file and updating the docs.

**Comment by AlexanderProd** [comment]
Hi @dasdachs ,
Thanks for letting me know, I didn't even notice it since I'm using Node 10. Can you create a PR for the `.nvmrc` file because I'm not using NVM. 
Appreciate your help.

**Comment by Joel-Torres** [comment]
Hi,
I could not deploy either to netlify. I tried to deploy on Heroku and the error message it gave me helped. I guess netlify needs to know what version of Node.js to download and "node": "=> 10.13 < 10.11" was not being accepted. I changed the node version from package.json file to the latest node and it finally worked. Can someone explain to me why exactly this worked.
"engines": {
    "node": "12.14.0"
  },

**Comment by dasdachs** [comment]
I would guess it uses the package.json config, although their [docs](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript) don't mention it. 

A alternative solution would be to fix the version in `.nvmrc` to 10.x.
