### ISSUE TITLE
auth/login/register

### ISSUE THREAD

**Issue by theskillwithin** [AlexanderProd/gatsby-shopify-starter#56]
sorry not really an issue more of a question

but I would like to be able to do login/register in gastby shopify app. 

but I cannot seem to find in the api's docs how to do

**Comment by hudsonandtask** [comment]
@theskillwithin if using this starter you'll need to write Auth/login custom. 

This starter uses the Shopify-buy SDK and that SDK doesn't have methods for returning the customer. 

You can write you own graphql queries and using a client in the store context make queries to your store to create/auth customers.

**Comment by AlexanderProd** [comment]
you would have to write your own backend to login and register.
