### ISSUE TITLE
update to "gatsby-plugin-sharp": "^2.7.1",

### ISSUE THREAD

**Issue by lexstefan** [AlexanderProd/gatsby-shopify-starter#63]
https://github.com/AlexanderProd/gatsby-shopify-starter/blob/1f9a8f9bc339a8a591cc7fa1d1c025dba03042eb/package.json#L21

imposible to get going with this starter on ubuntu 20 while that old version of sharp is installed

**Comment by AlexanderProd** [comment]
Thanks for letting me know! If you want you can create a PR with the upgraded plugin.
