### ISSUE TITLE
Adding/Removing Items from Cart on Checkoutpage

### ISSUE THREAD

**Issue by osseonews** [AlexanderProd/gatsby-shopify-starter#68]
After adding items to the cart and going to the checkout page on shopify, the user is not able to edit items in the cart on the shopify checkout page. In order to add/edit items, it seems that you need to go back to the cart page (on the gatsby page), edit items in the cart there, and then checkout again. This is confusing for a customer. Is there a way to allow the customer to edit cart items on the actual shopify checkout page?

**Comment by AlexanderProd** [comment]
No this is not possible.

**Comment by heytulsiprasad** [comment]
I think it's upto shopify to allow that or not, it can't be configured from code.
