### ISSUE TITLE
Problem with cart initialization when deployed CDN (AWS Cloudfront)

### ISSUE THREAD

**Issue by kertzi** [AlexanderProd/gatsby-shopify-starter#80]
Hello,
First thank you for this great starter! 
Then to the problem:
I'm not sure if this actual bug but I have odd behavior when I deploy my site to AWS. I use CloudFront as CDN and all site
files are stored in s3 bucket which is configured as origin for CloudFront. 

Now when I go to my site, cart/checkout doesn't get initialized fully. I have monitorized this from browser developer tools and I can see there is no checkoutId put in localstorage. So now when adding stuff to cart it throws error because checkoutId is undefined/null so Id is not added to react context either. 

I have debugged that so far that it starts to initialize checkout in ContextProvider but 
`isRemoved.current` is set to true before it hits to `setCheckoutState(..)`. It's weird why isRemove even get set to true.
If understand code correctly it's there to track when app unmounting/unmounted.

Link to code line i'm talking about: [Link](https://github.com/AlexanderProd/gatsby-shopify-starter/blob/master/src/provider/ContextProvider.js#L61)

On local development mode all works great. 

Thanks for any help.

**Comment by AlexanderProd** [comment]
Hi, 

I'm glad you like my starter. This behavior sounds very odd indeed, could you maybe deploy it somewhere else as a test? For example Github Pages or Netlify. 

Yeah you're understanding it correctly `isRemove` gets set to true when the component unmounts.

**Comment by kertzi** [comment]
Okay, I find it. I think useEffect() is changed a bit in react 17 so. 
useEffect with unmounting callback should be written like this to work correct in react 17:
```
useEffect(() => () => {
      isRemoved.current = true
  }, [])
```
Dependency array must be set to something to prohibit react to call callback in each render.
