### ISSUE TITLE
Error while gatsby develop

### ISSUE THREAD

**Issue by jingxuan98** [AlexanderProd/gatsby-shopify-starter#9]
Having problems with this error once I first try to gatsby develop

Any solutions?

----------------------------------------------------------------------------------------------------------
C:\Users\USER\AppData\Roaming\npm\node_modules\gatsby\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

RangeError: Maximum call stack size exceeded
    at Array Iterator.next (<anonymous>)
    at Object.format (util.js:72:10)

**Comment by AlexanderProd** [comment]
This is a problem with gatsby check out #7
